# Generated by Django 5.1.5 on 2025-02-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('OWL', 'Owls'), ('BOK', 'Books'), ('CRE', 'Magical Creatures'), ('WAN', 'Wands'), ('QUI', 'Quidditch Supplies'), ('WWW', 'Everything a Mischief-Maker Could Possibly Want')], default='WWW', max_length=3),
        ),
    ]
